### ISSUE TITLE
能提供一个具体的使用示例吗？

### ISSUE THREAD

**Issue by whcn** [in66-dev/In-Prestissimo#2]
比如我想基于fast-rcnn做目标检测，应该怎么使用这个框架？

**Comment by wonderzy** [comment]
同问

**Comment by jxt1234** [comment]
您好，在 android 和 ios 目录下面分别有demo，可以重点看 android 的，是用 squeezenet 做图片识别。做目标检测的需要知道多输入和多输出用法，请详细看 InNetAPI.h ，跟caffe 相比，只是对输入多一个vUpload过程，对输出多一个 vDownload 过程，其他是一样的。
