### ISSUE TITLE
no source code?

### ISSUE THREAD

**Issue by xyoungli** [in66-dev/In-Prestissimo#5]
有计划开源吗？

**Comment by Sky10086** [comment]
这也是人家的极致优化的劳动成果,哪那么容易就开源的,至少得保住自身竞争力,没有掌握更好的技术之前,这个当然不会开源了

**Comment by jxt1234** [comment]
@lxy890123 您好，目前我们没有开源的计划，但这不影响库的使用。遇到问题可以提issue
